version: '3.9'

services:
  controller_tratta:
    build: 
      context: Services/Controller_tratta
      dockerfile: Dockerfile
    ports:
      - "5002:5002" #vedi, non lo so
    network_mode: bridge
    # networks:
    #   - my-network

  elaboratore:
    build: 
      context: Services/Elaboratore
      dockerfile: Dockerfile    
    ports: 
      - 5010:5010
    network_mode: bridge
    # networks:
    #   - my-network

  notifier:
    build: 
      context: Services/Notification
      dockerfile: Dockerfile
    ports:
      - "5003:5003" #vedi, non lo so
    network_mode: bridge
    # networks:
    #   - my-network

  rules:
    build: 
      context: Services/Rules_Database
      dockerfile: Dockerfile
    network_mode: bridge
    # networks:
    #   - my-network
    ports:
      - "5005:5005" #vedi, non lo so

  scraper:
    depends_on:
      - controller_tratta
    build: 
      context: Services/Scraper
      dockerfile: Dockerfile
    ports: 
     - 5012:5012
    network_mode: bridge
    # networks:
    #   - my-network
    #ports:

  user_controller:
    build:
      context: Services/User_controller
      dockerfile: Dockerfile
    # networks:
    #   - my-network
    ports:
      - "5000:5000" #vedi, non lo soù
    network_mode: bridge

  users:
    build: 
      context: Services/User_Database
      dockerfile: Dockerfile
    # networks:
    #   - my-network
    ports:
      - "5001:5001" #vedi, non lo so
    network_mode: bridge

# networks:
#   my-network: bridge
