version: '3'

services:
  controller_tratta:
    build: ./Controller_tratta/Dockerfile
    ports:
      - "5002:5000" #vedi, non lo so
    #networks:
    #  - my-network

  elaboratore:
    build: ./Elaboratore/Dockerfile
    #ports:
    #  - "5002:5000"
    #networks:
    #  - my-network

  notifier:
    build: ./Notification/Dockerfile
    ports:
      - "5003:5000" #vedi, non lo so

  rules:
    build: ./Rules_Database/Dockerfile
    ports:
      - "5005:5000" #vedi, non lo so

  scraper:
    build: ./Scraper/Dockerfile
    #ports:
    #  - "5002:5000" #vedi, non lo so

  user_controller:
    build: ./User_controller/Dockerfile
    ports:
      - "5000:5000" #vedi, non lo so

  users:
    build: ./User_Database/Dockerfile
    ports:
      - "5001:5000" #vedi, non lo so

#networks:
#  my-network:
