apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  # namespace: monitoring
data:
  config.yml: |-
    global:
      smtp_smarthost: 'smtp:587'
      smtp_from: 'Notifier.dsbd@gmail.com'
    route:
      receiver: alert-email
      group_by: [alertname]
    receivers:
    - name: alert-email
      email_configs:
        - to: 'prova_notifier@hotmail.com'
        
# kind: ConfigMap
# apiVersion: v1
# metadata:
#   name: alertmanager-config
#   namespace: monitoring
# data:
#   config.yml: |-
#     global:
#     templates:
#     - '/etc/alertmanager/*.tmpl'
#     route:
#       receiver: alert-emailer
#       group_by: ['alertname', 'priority']
#       group_wait: 10s
#       repeat_interval: 30m
#       routes:
#         - receiver: slack_demo
#         # Send severity=slack alerts to slack.
#           match:
#             severity: slack
#           group_wait: 10s
#           repeat_interval: 1m
 
#     receivers:
#     - name: alert-emailer
#       email_configs:
#       - to: demo@devopscube.com
#         send_resolved: false
#         from: from-email@email.com
#         smarthost: smtp.eample.com:25
#         require_tls: false
#     - name: slack_demo
#       slack_configs:
#       - api_url: https://hooks.slack.com/services/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sz4Qk
#         channel: '#devopscube-demo'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  # namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:latest
        args:
          - "--config.file=/etc/alertmanager/config.yml"
          - "--storage.path=/alertmanager"
        ports:
        - name: alertmanager
          containerPort: 9093
        resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
        # - name: templates-volume
        #   mountPath: /etc/alertmanager-templates
        - name: alertmanager
          mountPath: /alertmanager
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager-config
      # - name: templates-volume
      #   configMap:
      #     name: alertmanager-templates
      - name: alertmanager
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  # namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9093'
spec:
  selector: 
    app: alertmanager
  type: NodePort  
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 31000