apiVersion: apps/v1
kind: Deployment
metadata:
  name: controllertratta
spec:
  replicas: 1 #scegliamo numero di repliche
  selector:
    matchLabels:
      app: controllertratta
  template:
    metadata:
      labels:
        app: controllertratta
    spec:
      containers:
      - name: controllertratta-container
        image: samperi_volpe-controller_tratta #TO_DO nome immagine + versione
        imagePullPolicy: Never
        ports:
        - containerPort: 5002
        # Aggiungi le variabili d'ambiente se necessario
        volumeMounts:
          - name: controllertratta-data
            mountPath: /path/to/database/data #TO_DO percorso database

      volumes:
        - name: controllertratta-data
          persistentVolumeClaim:
            claimName: controllertratta-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: controllertratta-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Imposta la dimensione del tuo volume persistente

---
apiVersion: v1
kind: Service
metadata:
  name: controllertratta-service
  labels: #non so se serve
    app: controller_tratta
spec:
  selector:
    app: controller_tratta
  ports:
    #- protocol: TCP
    - port: 5002
      targetPort: 5002