apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: ingress
    # nginx.org/rewrites: "serviceName=user-controller-service rewrite=/"
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: myapp.com #TO_DO vedi, se vogliamo cambiarlo tipo con myapp.com bisogna inserire l'ip nella configurazione windows
    http:
      paths:
      - path:  /user(/|$)(.*)  #TO_DO vedi
        # pathType: Prefix
        pathType: ImplementationSpecific
        backend:
          service:
            name: user-controller-service
            port:
              number: 5000

      # - path: /slamanagerr(/|$)(.*)  #TO_DO vedi
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: slamanager-service
      #       port:
      #         number: 5014
