apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  # namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:2.11-2.0.1
        ports:
        - containerPort: 9092
        - containerPort: 9093
        env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INSIDE://kafka-service:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
        - name: KAFKA_LISTENERS
          value: "INSIDE://0.0.0.0:9092"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INSIDE"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-service:2181"


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /your/preferred/path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: kafka
---

apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  # namespace: kafka
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  type: ClusterIP

---
#esporre metriche di kafka
apiVersion: v1
kind: ConfigMap
metadata:
  name: jmx-exporter-config
data:
  jmx-exporter-config.yml: |
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    whitelistObjectNames: ["kafka.server:type=BrokerTopicMetrics,name=*"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmx-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmx-exporter
  template:
    metadata:
      labels:
        app: jmx-exporter
    spec:
      containers:
      - name: jmx-exporter
        image: bitnami/jmx-exporter
        ports:
        - containerPort: 5556  # Porta esposta da jmx_exporter
        volumeMounts:
        - name: jmx-exporter-config
          mountPath: /etc/jmx-exporter
      volumes:
      - name: jmx-exporter-config
        configMap:
          name: jmx-exporter-config
---
apiVersion: v1
kind: Service
metadata:
  name: jmx-exporter-service
spec:
  selector:
    app: jmx-exporter
  ports:
  - protocol: TCP
    port: 5556
    targetPort: 5556
