apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  # namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:2.11-2.0.1
        ports:
        - containerPort: 9092
        - containerPort: 9093
        env:
        # JMX PORT FOR KAFKA EXPORTER
        - name: JMX_PORT
          value: "9010"
        - name: KAFKA_JMX_OPTS
          value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka-service"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INSIDE://kafka-service:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
        - name: KAFKA_LISTENERS
          value: "INSIDE://0.0.0.0:9092"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INSIDE"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-service:2181"
      - name: kafka-exporter
        image: danielqsj/kafka-exporter:latest
        args:
          - "--kafka.server=kafka-service:9092"
        ports:
          - name: metrics
            containerPort: 9308


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /your/preferred/path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: kafka
---

apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  # namespace: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: inside
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: metrics
      port: 9308
      targetPort: 9308
      protocol: TCP
  type: ClusterIP

