apiVersion: v1
kind: ConfigMap
metadata:
  name: node-exporter-config
data:
  node-exporter.yml: |-
    listen_address: 0.0.0.0:9100

#apiVersion: apps/v1
#kind: DaemonSet #DaemonSet
#metadata:
#  name: node-exporter
#  namespace: monitoring
#  labels:
#    k8s-app: node-exporter
#spec:
#  selector:
#    matchLabels:
#      k8s-app: node-exporter
#  template:
#    metadata:
#      labels:
#        k8s-app: node-exporter
#    spec:
#      containers:
#      - name: node-exporter
#        image: prom/node-exporter
#        ports:
#        - containerPort: 9100
#        resources:
#          requests:
#            memory: "64Mi"
#            cpu: "250m"
#          limits:
#            memory: "128Mi"
#            cpu: "500m"
#        volumeMounts:
#        - name: proc
#          mountPath: /host/proc
#          readOnly: true
#        - name: sys
#          mountPath: /host/sys
#          readOnly: true
#        - name: rootfs
#          mountPath: /rootfs
#          readOnly: true
#      volumes:
#      - name: proc
#        hostPath:
#          path: /proc
#      - name: sys
#        hostPath:
#          path: /sys
#      - name: rootfs
#        hostPath:
#          path: /

---
kind: Service
apiVersion: v1
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  selector:
      app: node-exporter
  ports:
  - name: node-exporter
    protocol: TCP
    port: 9100
    targetPort: 9100

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
      - name: node-exporter
        image: prom/node-exporter:latest
        ports:
        - containerPort: 9100
        volumeMounts:
        - name: config-volume
          mountPath: /etc/node-exporter/
      volumes:
      - name: config-volume
        configMap:
          name: node-exporter-config

