apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  # namespace: monitoring
data:
  prometheus.rules: |
    groups:
    -name: alert
      rules:
      - alert: InstanceDown
      expr: up == 0
      for: 360m #6 ore down
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s  
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets: ['alertmanager.default.svc.cluster.local:9093']
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_endpoints_name]
          regex: 'node-exporter'
          action: keep
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
      - job_name: 'kafka'
        static_configs:
          - targets: ['kafka-service:9308']
      
#        static_configs:
#          - targets: ['node-exporter:9100']

#kubernetes_sd_configs:
#          - role: endpoints
#relabel_configs:
#          - source_labels: [__meta_kubernetes_endpoints_name]
#            regex: 'node-exporter'
#            action: keep
         
  #     - job_name: 'k8apiserver'
  #     kubernetes_sd_configs:  #TO_DO per l'API server
  #     - role: endpoints
  #     scheme: https
  #     tls_config:
  #       ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  #       insecure_skip_verify: true  # Required if using Minikube.
  #     bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  #     relabel_configs:
  #  - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
  #       action: keep
  #       regex: default;kubernetes;https

  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  # namespace: monitoring
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml #TO_DO non so se dobbiamo modificarlo
              subPath: prometheus.yml
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-storage-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  # namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9090'
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30000