apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: c:\Users\damih\AppData\Roaming\Code\User\globalStorage\othy1010.kompose\kompose.exe convert --out=c:\Users\damih\Desktop\Samperi_volpe\Samperi_Volpe\prova --file=c:\Users\damih\Desktop\Samperi_volpe\Samperi_Volpe\prova\docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zookeeper
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: c:\Users\damih\AppData\Roaming\Code\User\globalStorage\othy1010.kompose\kompose.exe convert --out=c:\Users\damih\Desktop\Samperi_volpe\Samperi_Volpe\prova --file=c:\Users\damih\Desktop\Samperi_volpe\Samperi_Volpe\prova\docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/prova-default: "true"
        io.kompose.service: zookeeper
    spec:
      containers:
        - env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          image: confluentinc/cp-zookeeper:latest
          name: zookeeper
          ports:
            - containerPort: 2181
              hostPort: 2181
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: c:\Users\damih\AppData\Roaming\Code\User\globalStorage\othy1010.kompose\kompose.exe convert --out=c:\Users\damih\Desktop\Samperi_volpe\Samperi_Volpe\prova --file=c:\Users\damih\Desktop\Samperi_volpe\Samperi_Volpe\prova\docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    io.kompose.service: zookeeper
status:
  loadBalancer: {}

# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: zookeeper
# spec:
#   serviceName: zookeeper
#   replicas: 1
#   selector:
#     matchLabels:
#       app: zookeeper
#   template:
#     metadata:
#       labels:
#         app: zookeeper
#     spec:
#       containers:
#       - name: zookeeper
#         image: confluentinc/cp-zookeeper #TO_DO immagine del nostro zookeeper
#         ports:
#         - containerPort: 2181
#         volumeMounts:
#         - name: zookeeper-data
#           mountPath: /data

#   volumeClaimTemplates:
#   - metadata:
#       name: zookeeper-data
#     spec:
#       accessModes: [ "ReadWriteOnce" ]
#       resources:
#         requests:
#           storage: 1Gi